// <auto-generated />
using System;
using AutoInfo.DLL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AutoInfo.WebAPI.Migrations
{
    [DbContext(typeof(CarReportDbContext))]
    partial class CarReportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("AutoInfo.Domain.Models.Car", b =>
                {
                    b.Property<Guid>("VIN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("VIN");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            VIN = new Guid("654a3254-900a-4910-9923-8749460f685e")
                        });
                });

            modelBuilder.Entity("AutoInfo.Domain.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("VIN")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AutoInfo.Domain.Models.Report", b =>
                {
                    b.HasOne("AutoInfo.Domain.Models.Car", "Car")
                        .WithOne()
                        .HasForeignKey("AutoInfo.Domain.Models.Report", "VIN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
